export const translate = {
    'Dashboard': 'Trang chủ',
    'Scan History': 'Lịch sử quét',
    'Live Capture': 'Live capture',
    'Scan': 'Quét file',
    'Users': 'Người dùng',
    'About Us': 'Về chúng tôi',
    'Settings': 'Cài đặt',
    // '': '',
    'Filter': 'Lọc kết quả',

    'Drag & drop some files here, or click to select files': 'Kéo thả để upload hoặc click để chọn file',
    'Checking': 'Đang quét',

    'Malicious files detected': 'Tổng số file mã độc đã quét được',
    'IPs containing malicious files detected': 'Số IP phát hiện có chứa mã độc',
    'Top malicious URLs detected': 'Top malicious URLs detected',
    'Total requests detected': 'Total requests detected',
    'Total malicious URLs requested': 'Tổng số lượt request đến URL độc hại',
    'Total requests to malicious URLs': 'Tổng số lượt URL độc hại được truy vấn',

    'Traffic sent': 'Lượng traffic',
    'Files captured': 'Tổng số files bắt được trên đường truyền',
    'Connections to malicious URLs': 'Lượt kết nối đến URL độc hại',
    'Total traffic sent': 'Lượng traffic',
    'IP sent most traffic': 'Top các IP gửi nhiều traffic',
    'Most attacked protocols': 'Protocols bị tấn công nhiều nhất',

    'IP detected most malwares': 'Top các IP bị phát hiện chứa nhiều mã độc',
    'Total malwares detected': 'Tổng số mã độc phát hiện được',
    'Top IP attacked with malware': 'Top các IP bị tấn công bằng mã độc',

    'Basic settings': 'Cấu hình',
    'Sandbox': 'Sandbox',

    'Show': 'Show',

    'Model': 'Mô hình',
    'Engines': 'Engines',
    'HAN': 'HAN',
    'VirusTotal': 'VirusTotal',
    'Cuckoo': 'Cuckoo',
    'asm_cnn': 'asm_cnn',
    'asm_lstm': 'asm_lstm',
    'bytes_cnn': 'bytes_cnn',
    'bytes_lstm': 'bytes_lstm',
    'img': 'img',
    'ngram': 'ngram',

    'Search file name or hash code': 'Tìm theo tên file hoặc mã hash',

    'Virus Scanner': 'Kiểm tra mã độc',
    'Upload File': 'Tải lên tệp',
    'Limit size': 'Kích thước tối đa',

    'Size': 'Kích thước',
    'Time received': 'Thời gian',
    'Status': 'Trạng thái',
    'OK': 'Bình thường',
    'DANGER': 'NGUY HIỂM',
    'File type': 'Định dạng tệp',
    'File name': 'Tên tệp',
    'File path': 'Đường dẫn',
    'Detected by': 'Phát hiện bởi',
    'Scan time': 'Thời gian quét',
    'Source IP': 'Từ máy',
    'Destination IP': 'Đến máy',
    'Protocol': 'Giao thức',

    'Submission time': 'Thời gian submit',
    'Capture ID': 'Capture ID',
    'Submitted from': 'Gửi từ máy',
    'Details': 'Chi tiết',
    'History': 'Lịch sử',
    'Behavior': 'Hành vi',
    'Behavior report': 'Behavior report',
    'Download file': 'Download file',
    'Processes': 'Processes',
    'Signatures': 'Signatures',
    'Networks': 'Networks',
    'Others': 'Others',
    'Strings': 'Strings',
}